# Generated by Django 5.2.5 on 2025-08-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Descripcion', models.TextField()),
                ('Tecnologia', models.CharField(max_length=200)),
                ('F_Creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
